apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-api-v1
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: aggregator-api-v1-dev
          imagePullPolicy: Always
