apiVersion: v2
appVersion: v1
description: Aggregator service Helm chart
name: aggregator
type: application
version: 0.2.9
maintainers:
  - name: ashutosh-18k92
    email: ashutosh@example.com
    url: https://github.com/ashutosh-18k92
