# Chart Metadata
# This file allows the feature team to control which version of the base API chart to use

# Chart version from sf-helm-registry
chartVersion: "0.1.0"

# Chart repository
chartRepo: "https://github.com/ashutosh-18k92/sf-helm-registry.git"

# Chart path within the repository
chartPath: "api"
