apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Helm chart inflation - Production uses v0.2.0
helmCharts:
  - name: api
    repo: https://github.com/ashutosh-18k92/sf-helm-registry.git
    version: v0.2.0 # Production can use different version
    releaseName: aggregator
    namespace: super-fortnight
    valuesFile: values.yaml
    includeCRDs: false

# Namespace
namespace: super-fortnight

# ConfigMap for production
configMapGenerator:
  - name: service-config
    literals:
      - PORT=3000
      - SERVICE_NAME=aggregator-service
      - LOG_LEVEL=error
      - NODE_ENV=production

# Patches for production
patches:
  - path: patches/deployment-affinity.yaml
  - path: patches/hpa-scaling.yaml
  - path: patches/production-resources.yaml
