# Development Environment Configuration
env: development
overlay: development # the name of the overlay directory
targetRevision: developmnet # the branch or release to refer
namespace: super-fortnight #-dev
