---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-sealed-secret
  namespace: default
spec:
  encryptedData:
    api-key: AgAtRByGmWjg9xO9mQWKaiS/XJqNXUOyk0IFObhlFGC8HnJUz3tS++AmJmDHl163ZKM0UX7fj2PSQqTD4hiXhks5YEiOqVEPmPPp6Gatr61p3ske8wdH1um+SiPaIF+6neDrU9nDzwwzVd0Qz1wlSp4fbZXIm8/A+ETq+jSYOc7j50koe9H7BxlU1MMgZ4uJN9VPrBNZlAK+Flxz8ZdH8S5q4PuIbHvR6dXqRcB0KUwfwWCgXFnb64aHEnlino/VMHXNKW6qBlv09Lx4jC5BmYnhub2WqyVl5PU1FF9nPsP0mQ8GpMTS+cPDGeo8B1e7+pGoC6Hl2WI3+AF4iTJTkjstNSfBxRYv6Cyy70b56XEsbXVYzXFaMoruQXvL30c96H/TZ2+DL4pduTQhmB9/gI49YLsynxBhQXi9Bk8OcaY8zTqTW7mMHB0Uv0Ebzq9kjb+U0fB8vdNp7Hk/cTKW+t6DLwdRPYQv4GyUMbEiOmf5WceLCo/xNJJyQGGBaBXd1w7reqH/doJ2sB+NFtPBHaq4JwHnBwFV0Y5izGlwl9CJNGqExYjXEn0OUbxh7AQd5wnZ6eOT5C8NuK73p9ZchuKROjjEEVoVeunTlS+AEwEs4fNvHxhGmv+8xSolS9mdyjlIGSNKmCjd8OQe2C56URRwePlYmJsNroBYILPUwkLbjicaDNX7S08Ba9xRTPfjLnrqlC4/69awIE28Cqw0ct6a75vefQ==
    database-password: AgAL1IfRLvz3Qvv6xwcsCiGjG+R18IUFtIDbdkKEMYFB8g7Aw2bQRwjguiFjCSE0AaMZ5ox+ginCkD+4Z95adTynO92ACkfTuH1dDGCAjc7yWkQ1h1FLpuaR/rnbk+zyDNNi2QVlcVNzRgk8VtVVKJLgQ8BpeHETFPvdEnv+aNXoH5Id4VCUBs5X6Uda4B5oQrQC9HQZXh0wOnjdtNnvAFfWHtUajAWqCl+qgwFcBnYtmDDgiFwCTLn19FYYXKOhuCSjjImrlXRBUEMuOb+yvOA4gMTeZHptU6eXD8vfR/49j4KK5VAuoIB98nR3a8ftKnTZgs+YRKuOsoDVYhtmh/u2BnLoPKrlT+kQ9p2/OH5RPO8/j0Q4VjhkEaWfcFvnK3RQ+imLeGYSqYFNTHglhJlVX+DN0dUg9I4a8Q1tLCMXLt+oUv2o0lKiMA6LFUjKq+aCNW0frgrNHCWSTuo1w0Sc4O5bmRJLcqOmLraS8agF9ZDnGxxSfnWKUfs7VpXQZeTiOPYRnvzesMtO3F79Cl6L/gzWq100Pf3qhGXkNe/tBb6l4NEwUA+nuxklnS14KS9lp84CydUYz8zmTxIWQU1qf60A+qMBPbabcyoKaS2NDQ3yIlSo9Dxmj2YUQOGTXH0T/7tsALYbg+UXiog6vr9028K0U1ny1C2nCfrBlwfrFnproUNGCQ9liifs3163uiO3DYv7isL+K3zss4MZE52rHYsVDg==
  template:
    metadata:
      name: dev-sealed-secret
      namespace: default
    type: Opaque
