---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev-sealed-secret
  namespace: super-fortnight
spec:
  encryptedData:
    api-key: AgCHdY/W2pj8tczLlGkCUfH0/1KH6hUUEfMmG37ECbmzNALu9zx5iUM7r7tsvvCSN9lw0N7jqaJVGBtRfDssb11wcZWxBRAkrWxLhNOEoJbj1L0LnQO0bml7DSdrkgCclJSg6vdNSR1kdejq3lntHlvwrqkrMcSmemewvu/y9cVOn+EV2VFu42eWLZsOsJJSnZCrKLR54WCFkjhE1o1ZUVjEJIOvslv8Dv9s6Z/L7XQ7rHk1KKOsZAjMU/OeguoTvR+ctetaOuU6UWOxRh1vsnydLa4u90o1E8iytWF3VYuaMZK9VAnGdzIfMJlGc7oauNAngrFjea0pYlsGCPHAsNFQtyqv17jNWm3FKQQMK4ntCTqrPzmvttDUGulTCSfsnmGp/Q0zWNe1VK6oEqzt669TvFRvyQGAe27lQ+kHNhQZ4xWiCM/GTEXGqKO/SIlHODAZz/LfRVQCKfJoFA+9F1uEchaF+SE7S1FM57IYyEJOAVjC7XrwQw7ROuVQRHdPJs5klaheYhELh8RWgpt3D2BwBj+69ADvb3Ui46pjcwIBK3skigUI8CPKBwgyn719uj+pWf+4GClChaaCg9LDNVS7eNo9UyjBeiuUJk6rhcLUH8TqCfk8v9daVl3FulQETN9iFQlOdrvE5xYkPTDHw/cHTHf7wfFaosSCzJlUSMCkPhtQ40TONtKx4dlo4S1R66hgegDljPBTCmZhsjY9TWefqnxYwQ==
    database-password: AgA6H3h3Zbq0CLP9ISC7PWRdxBvqoq8RGkFtdrpAbep2XBuFfSmu4mr3xqFEpJymsODzc/jSXUo4hK/XTy69Vvutx88qigtjIGnbH5eqdKIWKp2P+0TpUcWP33mHo5U4gA2FvCwVaapuSjPp4wdYqSP3rYtRkSigYluTWU5secuIKVsdTZxELfq+5Hto9guKxrxJfJVUAxL6YI5l0tg18ai4cTewXi0F3sqk+b+213/wA+V1Vn1ty5Dt7T2BUjtGQR5Y2KbFaqU1Drg/Mr7daTxA56jcfd97Wiaz+VdBwwduDL0mjg61HdCGJIf3TN9IjWieKvLRe7h5hIB+3N1x2d+G9bo/eCngO+66ufXrvA7QTvPQBzQ/43t3gf2s7IkiIBlHJ6Xn0/mpNu2SMZkNlxi69JjaoJSRiOsqn6Dx4NtdBJmrF38xV73IF6rT5CTgALUO9O6oRpnr3mNSmrL3x6gfYSLEE1FBtRH1KSbQDrM1x9q7agLrrw0VgDjuvYIb91Z049/2qV7NcrWnFh39SkCLASq97ZAz/dFXT8nLO9YZdnzA7P01mGpzsqsxFU71VqdNTAFvRtejMvVEsXw6HI/lzYGZ85iui/1qqJ+/70snyLvPEMbw+tpCN+F+wWwYzRGowXZAMdxC3Y5X209LcaKbv2+XQPNOxkSuH920OhqDh1mLcI6LYyGis+eYirey2m12woXR8EdSRKWMANMM3JkxlQeYAA==
  template:
    metadata:
      name: dev-sealed-secret
      namespace: super-fortnight
    type: Opaque
