---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prod-sealed-secret
  namespace: default
spec:
  encryptedData:
    api-key: AgB9Vv/wPJGEFC+iKdsuKw3SiqwL623U0H6ypRYR7tTOUl4rOEejVNSwlUpBW/6t1Cc2Clf4X48fT5EzRbeP9eMhg1yfSEASiUutEtioABOMllv7JRnOX3r57XUr5zf4WW4DHdJzYvpQPjYG7zVsLR8GBTkXiFhS1aFrMuOgLoUalxo20n+RgoxIgLGFeoIlIGOhE5HhQs4ynf2idzRafFAXb6CvlZlHUzbMxAqu0ukCB+qvBSS3/6B4+ofWJdeUlWz5akxzlUeKByaFQusXw2Xjxre7y+5LNH5Z2r4EpgHvRxno2aHJnIiFIFHc/Ycc+G5WmZY5bZPH2XUirX3hSZ7piNGMjuVxqKP5uO8BZ1NnVjIRGizydjeB3UI/r9+eqODefMoSNeYkn9nHpxkV5zwXP8qMyfY6OWL0x+u+rTjirjm0pUKRydxiR38Ew5vtLeo447ZJhg6+/VKYotxkBVYFyOYdoRrDHKcR66efFvYUyF8FBy0T4p02RC9D/f/ejR7UHEKsaQSS7/hONeFsgFc2CrTOkyUCFxnRaifRlg2SEks6iBdU1kR5rTXkF7AqPcdXj7GsezY3N92S31KVmgL1UgVSg1GdkY/GnFfT596hcZ/Z4Tz1sk8yABhoAUNBWFZOg7UgzIfEbm+ZddhaAGLIEV6GCeA6MgT1OkoJ9Hpe8Qq2C4q4qmKhnjrJcEL1KO/l1Ab6n8BIW/iqlnEMHj5ir0eiuA==
    database-password: AgCFdP4rmkoltubXXFvim2rnETjDGMHOKfmibD6i4+4Z9L0QmjRyxIXDVhSMIJ4fOVedMK72xNOGnY1o6cwJ8ejZbHDHk3IZ9NYwEKgQlcLs+Ut5XU7TtsGIS3s9C/FY36XWNQ+6sZTKECoxDcGEhfeEGOjvX3mP+BZYvnT/I5c5MEzxXkqoW1FCp+GNMAEmNOHVrPBthbDRXMMAjUvaxiEfy+lJLEMycP+vqSvpzl+0G8hLKKYJ8/sQDe8bxRRx1zyg3jOZB2wDeDr0rpJAfgiDbr1v3kTNO6yCB4hU1IuBczIWPmxh4uhYcfCqKEFW0l8Ym7GrEWQlcD0FE7RUFecyTeCNfltgirUgtk3kk6kjLiV4CtjA/4H6Vkurz6gZUBb4UrqW6b0vNdm5kIjtcf44ONJ+PF4YOmq0qu5bbj3BFv2lO7Ag8uyJd1szqmWykMAZg2wSKTkeuf/OK+uaK9RoxNP3/QnLjR121ONXgoCJ4JGeyt5/8zWj+SAGg0RnkROmVrRjraDP6mDIUkzgpddvcEeK4jCxY+AIA5WppIHQyTDQUHwxpXU+Cl5/Lp0K5uoA7NpDku8rGuaER33EuiJJjMsKmgbt4udqZGPJ/kPT+VlQtFw/aRzpEBufbJSvNAm/PaMXvSY5I6HBvIOGVloVLMBew8KSsi5Dlu6DNTFH6CGfI9U4HsvN7ESPjZNB+OMcKIEft0Di1mw9OGEudxmjKpRT0g==
  template:
    metadata:
      name: prod-sealed-secret
      namespace: default
    type: Opaque
